[package]
name = "bpf-obj-dump"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
errno = "0.2.8"
libbpf-sys = "0.6.1-2"
thiserror = "1.0.30"
bpf-inspect-common = { path = "../bpf-inspect-common" }
