[package]
name = "bpf-obj-dump"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[features]

[dependencies]
errno = "0.2.8"
thiserror = "1.0.30"
bpf-rs = { path = "../bpf-rs" }
libbpf-sys = { git = "https://github.com/mdaverde/libbpf-sys.git", branch = "bpf-rs" }
