[package]
name = "bpf-obj-dump"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[features]

[dependencies]
errno = "0.2.8"
libbpf-sys = { path = "../libbpf-sys" }
thiserror = "1.0.30"
bpf-rs = { path = "../bpf-rs" }
