[package]
name = "bpf-rs"
version = "0.0.8"
edition = "2021"
homepage = "https://bpfdeploy.io"
description = "A safe, lean library for inspecting and querying eBPF objects"
keywords = ["bpf", "ebpf"]
readme = "README.md"
license = "BSD-2-Clause"
authors = ["Milan <milan@mdaverde.com>"]

[dependencies]
num_enum = "0.5.7"
thiserror = "1.0.30"
libbpf-sys = { version = "0.7.1", package = "bpfdeploy-libbpf-sys" }
serde = { version = "1.0.136", optional = true, features = ["derive"] }
bpf-rs-macros = { version = "0.0.1", path = "../bpf-rs-macros" }

[features]
serde = ["dep:serde", "bpf-rs-macros/serde"]
