[package]
name = "bpf-rs"
version = "0.0.1"
edition = "2021"
description = "A safe collection of eBPF utilities"
categories = ["bpf", "ebpf"]
readme = "README.md"
license-file = "LICENSE"
authors = ["Milan <milan@mdaverde.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
thiserror = "1.0.30"
libbpf-sys = { version = "0.7.0", package = "bpfdeploy-libbpf-sys" }
