[package]
name = "bpf-rs"
version = "0.0.0"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
thiserror = "1.0.30"
libbpf-sys = { git = "https://github.com/mdaverde/libbpf-sys.git", branch = "bpf-rs" }
