[package]
name = "bpf-feature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caps = "0.5.3"
nix = "0.23.1"
thiserror = "1.0.30"
