name: Rust

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo build --verbose --all-features
    - run: cargo test --verbose --all-features
