name: Rust

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: deps for libbpf
      run: sudo apt-get install -y clang-12 libelf-dev zlib1g-dev
    - run: cargo build --verbose --workspace --all-features
    - run: sudo -E "PATH=$PATH" $(which cargo) test --verbose --workspace --all-features
    - run: cargo fmt --check
